dataset:
  root_dir: D:/ToCo-main/datasets/coco/MSCOCO
  name_list_dir: F:/DAGNet/datasets/coco
  num_classes: 81
  crop_size: 320
  resize_range: [512, 2048]
  rescale_range: [0.5, 2.0]
  ignore_index: 255

work_dir:
  dir: work_dir_coco
  ckpt_dir: checkpoints
  pred_dir: predictions
  segs_dir: segs
  tb_logger_dir: tb_logger

train:
  split: train
  samples_per_gpu: 8 #4  #8
  max_iters: 80000
  cam_iters: 5000
  eval_iters: 10000
  log_iters: 200

#  max_iters: 1
#  cam_iters: 1
#  eval_iters: 1
#  log_iters: 1

val:
  split: val

optimizer:
  type: AdamW
  learning_rate: 2e-4
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 50
  warmup_ratio: 1e-6
  power: 1.0


clip_init:
  clip_pretrain_path: F:/DAGNet/pretrained/ViT-B-16.pt
  embedding_dim: 256
  in_channels: [768, 768,768,768]
